name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      
    - name: make ipa
      run: make
    - uses: actions/upload-artifact@v3
      with:
       name: iPA
       path: pissra1n.ipa
